### ISSUE TITLE
SagePay Line item issue

### ISSUE THREAD

**Issue by vdubbervan** [andyplak/events-manager-pro-sage-pay#17]
Hi andyplak,

I am struggling with an issue in the Sagepay add on.
When multiple tickets are purchased through SagePay the individual prices in the basket are diplaying the same value as the total price for all the tickets.

It seems there is an issue with the individual line items each displaying the total basket value.

Could you possibly tell me where to start with fixing this issue.

Regards,
Van.

**Comment by andyplak** [comment]
hi @vdubbervan 

Thanks, good spot. I'd not realised the line items were wrong. I'm short on time (as always) but I've had a quick stab at this in the devel branch. Checkout that branch and give it a test. See the commit above for what I've changed.

The figures in the basket will need number_formatting. It will also need testing on the different Events Manager tax settings, and also on with multi bookings enabled and disabled before  I merge it into the master branch. Feel free to pull request if you make further improvements.

Either way, let me know if that is in the right direction to fixing it.

Andy

**Comment by vdubbervan** [comment]
Hi Andy,

Thanks for getting back to me.
Your fixes seem to have done the job, I just need to figure out how to do the number_formatting for Item Tax, Item total and Line Total.

Thanks again,
Van.

**Comment by vdubbervan** [comment]
Ok I have found a little problem.
i have completed the payment process and in the bookings in the back office my booking is marked as approved.
If I view the details of the booking it is marked as approved too.

However I am only receiving Booking Pending emails, If i resend the the email to my self I stiil get the Booking Pending Email.
If I then change the booking status, select "approve"d and then resend the email I receive the Booking Confirmation msg.

Do you have any ideas what might be causing this?

(This was working previously, I don't see how the updates would have any affect on this part of the process).

Thanks,
Van.

**Comment by vdubbervan** [comment]
it looks like the booking status is not being saved in the EM_BOOKINGS table even though the correct "approved" messages and labels appear in the bookings forms in the back office.

**Comment by andyplak** [comment]
@vdubbervan I've not seen this behavior myself, although someone mentioned something similar recently. I'll have a go at trying to reproduce, although it will be the weekend before I get a chance now. Let me know if you make any discoveries in the meantime.

**Comment by vdubbervan** [comment]
Hi Andy,


Thanks for coming back to me.

I'm sure it won't be anything major as it's 99% there but you know the code better than anyone so I'm sure you will find a fix.


Let me know how you get on as I have a client chasing me daily on this, I've told them to manually approve the transactions for now.


Something else you might want to add is to update the VPSProtocol? to version 3.00 as SagePay are stopping support for anything below that.


Regards,

Van.


________________________________

**Comment by andyplak** [comment]
@vdubbervan I've updated the code in the devel branch to include the number formatting for the basket.

I've also tested in single and multi booking user mode and I am getting the Booking Confirmed emails as expected, and the booking is marked as approved, however the transactions are not being recorded which is most odd. This was working previously so I wonder if something has changed in EM or EM Pro. Will continue to investigate.

**Comment by andyplak** [comment]
New issues opened for tracking:
#18 VPS Version Upgrade
#19 Transactions not being recorded

**Comment by vdubbervan** [comment]
Hi Andy,
Thanks for your efforts, they are greatly appreciated.
I just noticed this morning that the transactions were not being recorded, this is causing quite a big problem on my clients site as they have events live and are taking payments through SagePay.

Are you able to give me a very rough estimate as to when you think you might have a fix for this?
I'm not being pushy I just want to go back to my client with a solid argument.

Thanks again,
Van.

**Comment by andyplak** [comment]
@vdubbervan By the end of the week latest. Hopefully sooner. See #19 for updates.
