### ISSUE TITLE
Transactions not being recorded on successful payment

### ISSUE THREAD

**Issue by andyplak** [andyplak/events-manager-pro-sage-pay#19]
handle_payment_return is marking orders as approved as expected, but no transaction is recorded. This is a regression as was working previously.

**Comment by andyplak** [comment]
`$wpdb->insert( $table, $data )` in parent events-manager-pro/add-ons/gateway/gateway.php in the record_transaction function is returning false, yet no sql errors errors are reported.

**Comment by vdubbervan** [comment]
WordPress has just released a brand new update too (4.0.4).
This seems to coincide with the transactions not being recorded.

**Comment by andyplak** [comment]
wpdb->insert is throwing an error after all:

`WordPress database error  for query SHOW FULL COLUMNS FROM `wp_em_transactions` made by do_action('wp_ajax_em_payment'), call_user_func_array, EM_Gateways::handle_payment_gateways, do_action('em_handle_payment_return_sagepay_form'), call_user_func_array, EM_Gateway_SagePay_Form->handle_payment_return, EM_Gateway->record_transaction`

**Comment by andyplak** [comment]
@vdubbervan which versions of WordPress, EM and EM Pro are you running?

**Comment by andyplak** [comment]
Found it... Security patch in 4.2.1 added a new function, 'wpdb->process_field_lengths()', that causes an insert or update query not to be run if the data is longer than the permissible size based on the database schema.

As we know from #11, the Sage Pay transaction IDs are longer than EM allows us to store in the transaction. So, since WP 4.2.1 Sage transactions will no longer be saved.

**Comment by andyplak** [comment]
@vdubbervan Can you try the latest code from the devel branch and report back on how it works for you?

**Comment by andyplak** [comment]
@vdubbervan Were you able to test out this fix?

**Comment by vdubbervan** [comment]
Hi Andy,

Apologies for not coming back sooner.
Yes we have tested your updates and all is working well, so many thanks for all your hard work on that.

Are you going to do a new release for the Sagepay Protocol v3.0?

**Comment by andyplak** [comment]
Great, thanks. I will, but won't be this week. #18 will track that. Will see if I can squeeze it in next week.

**Comment by vdubbervan** [comment]
ok cool, no worries, we've got until July anyway :)
Thanks again.
