### ISSUE TITLE
Error processing transaction

### ISSUE THREAD

**Issue by vdubbervan** [andyplak/events-manager-pro-sage-pay#24]
I have started recieving an error on SagePay when trying to process transactions.

Status: Malformed
Status Detail : 3114 : The BillingCity field is required.

I have not made any changes to the site, it seems to have just stopped taking payments.

You can test the issue yourself here:
http://www.surreyhills.org/events/the-2016-national-wood-fuel-conference/

I look forward to your response.

Van.

**Comment by andyplak** [comment]
@vdubbervan I suspect something has been changed in your forms editor. Are you using a different form for this event?

The field name for the city field on your form is currently `BillingCity`. That is not consistent with the other fields on your form which normally start with the default `dbem_` (you have as such elsewhere in the form: `dbem_country`, `dbem_address`, `dbem_address`, `dbem_zip`). I think as a result Events Manager is not aware of the city field being one of the "Common User Fields for Gateways", and is therefore not able to pass it over to SagePay.

See this as an example form setup:

![em-sage-config](https://cloud.githubusercontent.com/assets/540165/16275374/048e6290-38aa-11e6-9ee4-9c7d240fafbd.jpg)

![em-sage-config](https://cloud.githubusercontent.com/assets/540165/16275119/f9078e5c-38a8-11e6-89bc-ed0d48467d2f.jpg)

Have an experiment with the City field name there, and let me know how you get on.

**Comment by vdubbervan** [comment]
Hi Andy,

Thanks for coming back to me so quickly.
It is odd that this stopped working.

I edited the City field in the SagePay f form to match the user field and then in the “Common User Fields for Gateways” form, I matched the City fields up.

This has resolved the issue.

Thanks again.
Van.

**Comment by andyplak** [comment]
Great, glad to hear that's resolved it.
